// Copyright (c) 2020-2021 by the Zeek Project. See LICENSE for details.

#pragma once

#include <hilti/ast/forward.h>

namespace hilti::visitor {

class Dispatcher {
public:
    virtual void operator()(const hilti::Attribute&) {}
    virtual void operator()(const hilti::AttributeSet&) {}
    virtual void operator()(const hilti::Ctor&) {}
    virtual void operator()(const hilti::Declaration&) {}
    virtual void operator()(const hilti::Expression&) {}
    virtual void operator()(const hilti::Function&) {}
    virtual void operator()(const hilti::Module&) {}
    virtual void operator()(const hilti::QualifiedType&) {}
    virtual void operator()(const hilti::Statement&) {}
    virtual void operator()(const hilti::UnqualifiedType&) {}
    virtual void operator()(const hilti::ctor::Address&) {}
    virtual void operator()(const hilti::ctor::Bool&) {}
    virtual void operator()(const hilti::ctor::Bytes&) {}
    virtual void operator()(const hilti::ctor::Coerced&) {}
    virtual void operator()(const hilti::ctor::Default&) {}
    virtual void operator()(const hilti::ctor::Enum&) {}
    virtual void operator()(const hilti::ctor::Error&) {}
    virtual void operator()(const hilti::ctor::Exception&) {}
    virtual void operator()(const hilti::ctor::Interval&) {}
    virtual void operator()(const hilti::ctor::Library&) {}
    virtual void operator()(const hilti::ctor::List&) {}
    virtual void operator()(const hilti::ctor::Map&) {}
    virtual void operator()(const hilti::ctor::Network&) {}
    virtual void operator()(const hilti::ctor::Null&) {}
    virtual void operator()(const hilti::ctor::Optional&) {}
    virtual void operator()(const hilti::ctor::Port&) {}
    virtual void operator()(const hilti::ctor::Real&) {}
    virtual void operator()(const hilti::ctor::RegExp&) {}
    virtual void operator()(const hilti::ctor::Result&) {}
    virtual void operator()(const hilti::ctor::Set&) {}
    virtual void operator()(const hilti::ctor::SignedInteger&) {}
    virtual void operator()(const hilti::ctor::Stream&) {}
    virtual void operator()(const hilti::ctor::String&) {}
    virtual void operator()(const hilti::ctor::StrongReference&) {}
    virtual void operator()(const hilti::ctor::Struct&) {}
    virtual void operator()(const hilti::ctor::Time&) {}
    virtual void operator()(const hilti::ctor::Tuple&) {}
    virtual void operator()(const hilti::ctor::Union&) {}
    virtual void operator()(const hilti::ctor::UnsignedInteger&) {}
    virtual void operator()(const hilti::ctor::ValueReference&) {}
    virtual void operator()(const hilti::ctor::Vector&) {}
    virtual void operator()(const hilti::ctor::WeakReference&) {}
    virtual void operator()(const hilti::ctor::map::Element&) {}
    virtual void operator()(const hilti::ctor::struct_::Field&) {}
    virtual void operator()(const hilti::declaration::Constant&) {}
    virtual void operator()(const hilti::declaration::Expression&) {}
    virtual void operator()(const hilti::declaration::Field&) {}
    virtual void operator()(const hilti::declaration::Function&) {}
    virtual void operator()(const hilti::declaration::GlobalVariable&) {}
    virtual void operator()(const hilti::declaration::ImportedModule&) {}
    virtual void operator()(const hilti::declaration::LocalVariable&) {}
    virtual void operator()(const hilti::declaration::Module&) {}
    virtual void operator()(const hilti::declaration::Property&) {}
    virtual void operator()(const hilti::declaration::Type&) {}
    virtual void operator()(const hilti::expression::Assign&) {}
    virtual void operator()(const hilti::expression::BuiltInFunction&) {}
    virtual void operator()(const hilti::expression::Coerced&) {}
    virtual void operator()(const hilti::expression::Ctor&) {}
    virtual void operator()(const hilti::expression::Deferred&) {}
    virtual void operator()(const hilti::expression::Grouping&) {}
    virtual void operator()(const hilti::expression::Keyword&) {}
    virtual void operator()(const hilti::expression::ListComprehension&) {}
    virtual void operator()(const hilti::expression::LogicalAnd&) {}
    virtual void operator()(const hilti::expression::LogicalNot&) {}
    virtual void operator()(const hilti::expression::LogicalOr&) {}
    virtual void operator()(const hilti::expression::Member&) {}
    virtual void operator()(const hilti::expression::Move&) {}
    virtual void operator()(const hilti::expression::Name&) {}
    virtual void operator()(const hilti::expression::PendingCoerced&) {}
    virtual void operator()(const hilti::expression::Ternary&) {}
    virtual void operator()(const hilti::expression::TypeInfo&) {}
    virtual void operator()(const hilti::expression::TypeWrapped&) {}
    virtual void operator()(const hilti::expression::Type_&) {}
    virtual void operator()(const hilti::expression::UnresolvedOperator&) {}
    virtual void operator()(const hilti::expression::Void&) {}
    virtual void operator()(const hilti::statement::Assert&) {}
    virtual void operator()(const hilti::statement::Block&) {}
    virtual void operator()(const hilti::statement::Break&) {}
    virtual void operator()(const hilti::statement::Comment&) {}
    virtual void operator()(const hilti::statement::Continue&) {}
    virtual void operator()(const hilti::statement::Declaration&) {}
    virtual void operator()(const hilti::statement::Expression&) {}
    virtual void operator()(const hilti::statement::For&) {}
    virtual void operator()(const hilti::statement::If&) {}
    virtual void operator()(const hilti::statement::Return&) {}
    virtual void operator()(const hilti::statement::SetLocation&) {}
    virtual void operator()(const hilti::statement::Switch&) {}
    virtual void operator()(const hilti::statement::Throw&) {}
    virtual void operator()(const hilti::statement::Try&) {}
    virtual void operator()(const hilti::statement::While&) {}
    virtual void operator()(const hilti::statement::Yield&) {}
    virtual void operator()(const hilti::statement::switch_::Case&) {}
    virtual void operator()(const hilti::statement::try_::Catch&) {}
    virtual void operator()(const hilti::type::Address&) {}
    virtual void operator()(const hilti::type::Any&) {}
    virtual void operator()(const hilti::type::Auto&) {}
    virtual void operator()(const hilti::type::Bool&) {}
    virtual void operator()(const hilti::type::Bytes&) {}
    virtual void operator()(const hilti::type::DocOnly&) {}
    virtual void operator()(const hilti::type::Enum&) {}
    virtual void operator()(const hilti::type::Error&) {}
    virtual void operator()(const hilti::type::Exception&) {}
    virtual void operator()(const hilti::type::Function&) {}
    virtual void operator()(const hilti::type::Interval&) {}
    virtual void operator()(const hilti::type::Library&) {}
    virtual void operator()(const hilti::type::List&) {}
    virtual void operator()(const hilti::type::Map&) {}
    virtual void operator()(const hilti::type::Member&) {}
    virtual void operator()(const hilti::type::Name&) {}
    virtual void operator()(const hilti::type::Network&) {}
    virtual void operator()(const hilti::type::Null&) {}
    virtual void operator()(const hilti::type::OperandList&) {}
    virtual void operator()(const hilti::type::Optional&) {}
    virtual void operator()(const hilti::type::Port&) {}
    virtual void operator()(const hilti::type::Real&) {}
    virtual void operator()(const hilti::type::RegExp&) {}
    virtual void operator()(const hilti::type::Result&) {}
    virtual void operator()(const hilti::type::Set&) {}
    virtual void operator()(const hilti::type::SignedInteger&) {}
    virtual void operator()(const hilti::type::Stream&) {}
    virtual void operator()(const hilti::type::String&) {}
    virtual void operator()(const hilti::type::StrongReference&) {}
    virtual void operator()(const hilti::type::Struct&) {}
    virtual void operator()(const hilti::type::Time&) {}
    virtual void operator()(const hilti::type::Tuple&) {}
    virtual void operator()(const hilti::type::Type_&) {}
    virtual void operator()(const hilti::type::Union&) {}
    virtual void operator()(const hilti::type::Unknown&) {}
    virtual void operator()(const hilti::type::UnsignedInteger&) {}
    virtual void operator()(const hilti::type::ValueReference&) {}
    virtual void operator()(const hilti::type::Vector&) {}
    virtual void operator()(const hilti::type::Void&) {}
    virtual void operator()(const hilti::type::WeakReference&) {}
    virtual void operator()(const hilti::type::bytes::Iterator&) {}
    virtual void operator()(const hilti::type::enum_::Label&) {}
    virtual void operator()(const hilti::type::function::Parameter&) {}
    virtual void operator()(const hilti::type::list::Iterator&) {}
    virtual void operator()(const hilti::type::map::Iterator&) {}
    virtual void operator()(const hilti::type::set::Iterator&) {}
    virtual void operator()(const hilti::type::stream::Iterator&) {}
    virtual void operator()(const hilti::type::stream::View&) {}
    virtual void operator()(const hilti::type::tuple::Element&) {}
    virtual void operator()(const hilti::type::vector::Iterator&) {}
};

} // namespace hilti::visitor
