// Copyright (c) 2023 by the Zeek Project. See LICENSE for details.

#include <hilti/ast/all.h>
#include <hilti/ast/visitor-dispatcher.h>

using namespace hilti;

HILTI_NODE_IMPLEMENTATION_0(Attribute);
HILTI_NODE_IMPLEMENTATION_0(AttributeSet);
HILTI_NODE_IMPLEMENTATION_0(Ctor);
HILTI_NODE_IMPLEMENTATION_0(Declaration);
HILTI_NODE_IMPLEMENTATION_0(Expression);
HILTI_NODE_IMPLEMENTATION_0(Function);
HILTI_NODE_IMPLEMENTATION_0(Module);
HILTI_NODE_IMPLEMENTATION_0(QualifiedType);
HILTI_NODE_IMPLEMENTATION_0(Statement);
HILTI_NODE_IMPLEMENTATION_0(UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_0(ctor::map::Element)
HILTI_NODE_IMPLEMENTATION_0(ctor::struct_::Field);
HILTI_NODE_IMPLEMENTATION_0(statement::switch_::Case)
HILTI_NODE_IMPLEMENTATION_0(statement::try_::Catch)
HILTI_NODE_IMPLEMENTATION_0(type::enum_::Label)
HILTI_NODE_IMPLEMENTATION_0(type::tuple::Element)
HILTI_NODE_IMPLEMENTATION_1(ctor::Address, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Bool, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Bytes, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Coerced, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Default, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Enum, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Error, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Exception, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Interval, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Library, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::List, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Map, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Network, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Null, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Optional, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Port, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Real, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::RegExp, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Result, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Set, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::SignedInteger, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Stream, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::String, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::StrongReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Struct, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Time, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Tuple, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Union, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::UnsignedInteger, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::ValueReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::Vector, Ctor)
HILTI_NODE_IMPLEMENTATION_1(ctor::WeakReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(declaration::Constant, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::Expression, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::Field, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::Function, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::GlobalVariable, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::ImportedModule, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::LocalVariable, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::Module, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::Parameter, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::Property, Declaration)
HILTI_NODE_IMPLEMENTATION_1(declaration::Type, Declaration)
HILTI_NODE_IMPLEMENTATION_1(expression::Assign, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::BuiltInFunction, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Coerced, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Ctor, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Deferred, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Grouping, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Keyword, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::ListComprehension, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::LogicalAnd, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::LogicalNot, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::LogicalOr, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Member, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Move, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Name, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::PendingCoerced, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Ternary, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::TypeInfo, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::TypeWrapped, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Type_, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::UnresolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_1(expression::Void, Expression)
HILTI_NODE_IMPLEMENTATION_1(statement::Assert, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Block, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Break, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Comment, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Continue, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Declaration, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Expression, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::For, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::If, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Return, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::SetLocation, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Switch, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Throw, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Try, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::While, Statement)
HILTI_NODE_IMPLEMENTATION_1(statement::Yield, Statement)
HILTI_NODE_IMPLEMENTATION_1(type::Address, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(type::Any, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(type::Auto, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(type::Bool, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Bytes, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::DocOnly, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Enum, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Error, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Exception, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Function, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Interval, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Library, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::List, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Map, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Member, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Network, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Null, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::OperandList, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Optional, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Port, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Real, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::RegExp, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Result, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Set, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::SignedInteger, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Stream, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::String, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::StrongReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Struct, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Time, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Tuple, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Type_, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Union, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Unknown, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Name, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::UnsignedInteger, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(type::ValueReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Vector, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::Void, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::WeakReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::bytes::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::list::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::map::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::set::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::stream::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::stream::View, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(type::vector::Iterator, UnqualifiedType)
